version: "3"

services:
    server:
        build: ./server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
        command: npm run start
        depends_on:
            - mongodb
        env_file:
            - ./.env
    client:
        build: ./client
        ports:
            - "80:80"
        volumes:
            - ./frontend:/frontend

    mongodb:
        image: "mongo"
        volumes:
            - data:/data/db
        ports:
            - "27017:27017"

volumes:
    data:
