version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy App
          command: |
            # ssh @20.164.42.253 "cd /var/www/nodebackend/ && sudo git pull && cd /home/centos && sudo pm2 restart app"
            # ssh -i PUBLICKEY USER@IPADDRESS
            

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: dev