import img from "../../Assets/aimgp1.png";
export const articles = [
	{
		id: 1,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
		articleImg1: "",
		articleImg2: "",
		articleImg2: "",
		authorImg: "",
		author: "",
		date: "",
		para1: "",
	},
	{
		id: 2,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
	},
	{
		id: 3,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
	},
	{
		id: 4,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
	},
	{
		id: 5,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
	},
	{
		id: 6,
		title: "How To Write A Good Cover Letter That Wins",
		text: "This is an attempt to understand how to work with a layout that invloves working with a team and trying to make a unique design that flies. Interesting times.",
		image: img,
		time: "5 MIN READ",
	},
];
