name: React CI

on:
    pull_request:
        branches: ["dev"]

jobs:
    build:
        runs-on: [self-hosted,frontend]
        strategy:
            matrix:
                node-version: [ 16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Node LTS versions
              uses: msimerson/node-lts-versions@v1.1.1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              env:
                  FORCE_COLOR: 0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "./client/package-lock.json"
        
            - run: cd client && npm i    
            - run: pm2 restart frontend
